# Generated by Django 5.0 on 2024-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sentAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
